# Use the official Python 3.9 image from Docker Hub
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY myrestapis.py /app/myrestapis.py

# Run the Python script when the container starts
CMD ["python3", "myrestapis.py"]
